# Generated by Django 3.0.8 on 2020-07-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='ispopular',
        ),
        migrations.RemoveField(
            model_name='category',
            name='categoryurl',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='subcategoryurl',
        ),
    ]
