# Generated by Django 3.0.8 on 2020-07-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200727_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supliercontact',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='suppliertype',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
