# Generated by Django 3.0.8 on 2020-08-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_subcategory_haveproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannername', models.CharField(blank=True, max_length=200, null=True)),
                ('bannerimage', models.ImageField(blank=True, null=True, upload_to='')),
                ('bannertext', models.CharField(blank=True, max_length=200, null=True)),
                ('isactive', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
