# Generated by Django 3.0.8 on 2020-08-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_bannerimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimages',
            name='isactive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
