# Generated by Django 3.0.8 on 2020-08-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200816_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='region',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
