# Generated by Django 3.0.8 on 2020-09-01 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200901_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='order',
            field=models.OneToOneField(blank=True, limit_choices_to={'order__order_status': 'pending'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Order'),
        ),
    ]
