# Generated by Django 3.0.8 on 2020-09-03 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20200901_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Order'),
        ),
    ]
