# Generated by Django 3.0.8 on 2020-09-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20200904_0330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supliercontact',
            new_name='suppliercontact',
        ),
    ]
