# Generated by Django 3.0.8 on 2020-11-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20201121_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
