# Generated by Django 3.0.8 on 2020-11-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_product_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bengali_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
